### PR TITLE
Fix header not covering subtitle

### PR DESCRIPTION
**Pull request by squarefrog**
screen shot 2015-04-20 at 19 37 29

BWAAAAAHH!

====

screen shot 2015-04-20 at 19 39 33

phew

### CODE REVIEW

**Comment by squarefrog** [comment]
Is it bad that it took me longer to find appropriate gifs than to make the change?

**Comment by neonichu** [comment]
@squarefrog no, that's great 💖

**Comment by orta** [comment]
Hah, sorry to be the harbinger of bad news, but that's actually as designed! I want something to poke out so that it doesn't just appear out of nowhere. Sssoooorrrrry

**Comment by squarefrog** [comment]
In that case, how about a small drop shadow on the cover, or tiny pull tab?

**Comment by orta** [comment]
I would very likely take a subtle bottom border here, sounds like a good fix :+1:

**Comment by orta** [comment]
maybe apply a lighten to the highlight colour?

**Comment by squarefrog** [comment]
Can you run a stub of this locally? Browser inspection only gets so far..

**Comment by squarefrog** [comment]
screen shot 2015-04-20 at 20 01 33

1px solid looks nice... not sure about the opened state

screen shot 2015-04-20 at 19 59 43

I guess either:

- Connect the bottom border with the horizontal dividers
- Distance the separator from the bottom
- Match the 2px width?

**Comment by orta** [comment]
You can run cocoadocs locally, clone the repo, `bundle install` and run something like `bundle exec ruby cocoadocs.rb cocoadocs doc NYTPhotoViewer --verbose`

**Comment by orta** [comment]
I think 1px looks good, what about when it expands it animates to the white effectively hiding it?

**Comment by squarefrog** [comment]
:+1: yep that's work. I'll sort that tomorrow.

**Comment by orta** [comment]
Sorry @squarefrog but design dictatin' ;)

**Comment by squarefrog** [comment]
🎵 *They see me rollin'.... Dictatin'....*

**Comment by alloy** [comment]
@squarefrog lol

**Pull request closed without merging**
