### PR TITLE
Update Preview to work post sharing + Jazzy update

### PR DESCRIPTION
**Pull request by orta**
Doesn't fix the bug everyones mentioning in #488 - but does make it possible for other things to work

### CODE REVIEW

**Comment by orta** [comment]
Also now updates Jazzy to master - https://github.com/CocoaPods/cocoadocs.org/issues/488 https://github.com/realm/jazzy/issues/661#issuecomment-263131462

**Comment by groue** [comment]
Hello @orta. Reading your comments, I understand that #488 is currently deployed. Is that true? Because some pods are still in bad shape:

http://cocoadocs.org/docsets/GRDB.swift/0.92.0/index.html  http://api.cocoadocs.org:4567/error/GRDB.swift/0.90.1

If #488 has been deployed, I'll have to pig back https://github.com/realm/jazzy/issues/661

**Comment by orta** [comment]
Did you request a redeploy of the pod?

**Comment by orta** [comment]
looks like an issue with the deploy 

screen shot 2016-12-02 at 07 15 14

**Comment by orta** [comment]
I've fixed the deploy, and regenerated the docs - seems like everything working ( hah, the stats for the tests for this lib are out of the ballpark )

screen shot 2016-12-02 at 07 27 24

**Comment by groue** [comment]
Thanks @orta! The doc regeneration http://api.cocoadocs.org:4567/redeploy/GRDB.swift/latest has successfully done its job: http://cocoadocs.org/docsets/GRDB.swift/0.92.0/index.html 💯

**Comment by indisoluble** [comment]
Hi there,

I have tried to re-parse my library a couple of times with: http://api.cocoadocs.org:4567/redeploy/HRLEngine/latest, with no success. The documentation I can see: http://cocoadocs.org/docsets/HRLEngine/ is generated with AppleDoc, however the main language in my project is Swift.

When I first uploaded my code to the trunk most of the code was Objective-C but since then I fixed "this problem" and although I updated the version of the Pod many times and re-parse the library a couple of times, the documentation is still generated with AppleDoc instead of Jazzy.

Can you help me with this? Thanks.

**Pull request merged**
