### PR TITLE
Run prepare command

### PR DESCRIPTION
**Pull request by segiddins**
This is needed to resolve https://github.com/realm/realm-cocoa/issues/1197.

### CODE REVIEW

**Comment by orta** [comment]
:+1:

**Comment by segiddins** [comment]
Wait, I thought we agreed not to merge this, at least not until the sandboxing stuff was done?

**Comment by orta** [comment]
I wasn't planning on building that, and it's not like there are other ways of making CD exec arbitrary code.

**Comment by segiddins** [comment]
I know, but @alloy was working on it.

**Comment by orta** [comment]
best to not rely on alloy for things :P

**Comment by alloy** [comment]
This is definitely one of the things I will be working on, but not over the next few weeks or something.

**Pull request merged**
