### PR TITLE
Escape url for github podspec too

### PR DESCRIPTION
**Pull request by k0nserv**
@orta any other places you can think of?

### CODE REVIEW

**Comment by k0nserv** [comment]
[Here](https://github.com/CocoaPods/cocoadocs.org/blob/master/classes/docset_fixer.rb#L200-L226) maybe ?

**Comment by k0nserv** [comment]
[here](https://github.com/CocoaPods/cocoadocs.org/blob/master/classes/spec_extensions.rb#L14-L16) too probably

**Comment by orta** [comment]
Hrm, probably, those are the "folders" in s3, might be better to add an `escaped_name` method to the Podspec

**Comment by k0nserv** [comment]
Yeah that sounds like a good idea

**Pull request merged**
